version: '3'
volumes:
  user-data:
services:
  db_quickstart:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco-local
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3303:3306"